### ISSUE TITLE
Error: No period data for the given tx. Height:undefined

### ISSUE THREAD

**Issue by TimDaub** [leapdao/bridge-ui#249] opened 2019-11-05 09:26 UTC
## Scope

- To reproduce
  - Start your own local node and local bridge-ui
  - deposit 10 LEAP
  - UTXO shows up in UI and "Normal" exit button is clickable
  - Click the button. The following error appears: ```Error: No period data for the given tx. Height:undefined```

## Deliverables

- Fix

## Gains for the project

- No more confused users

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by troggy** [comment] 2019-11-22 11:17
> - deposit 10 LEAP
> - UTXO shows up in UI and "Normal" exit button is clickable

Cannot reproduce — UTXO shows up with disabled exit button (as expected).


> The following error appears: Error: No period data for the given tx. Height:undefined

However, this error may happen due to #252 (on localnet and testnet) or due to #253 (on a testnet, already fixed).

**Comment by johannbarbie** [comment] 2019-11-23 10:28
fixed by https://github.com/leapdao/bridge-ui/issues/253 , plz reopen if error reoccurs.

**Comment by troggy** [comment] 2019-11-23 10:34
likely because of #252 as #253 has nothing to do with local env

**Comment by troggy** [comment] 2020-04-06 19:52
closing in favour of #252

**Closed by troggy** 2020-04-06 19:52 UTC
Labels: Status: Available, Type: Bug, bounty
